### PR TITLE
Add the translation file zh_cn.json

### PR DESCRIPTION
**Pull request by Mai-xiyu**
Add the translation file zh_cn.json

### CODE REVIEW

**Comment by gisellevonbingen** [comment]
I can't find zh_cn.json file.
Seem missing commit what add zh_cn.json file.

**Comment by gisellevonbingen** [comment]
Could you try again as follow below steps?
1. go to https://github.com/gisellevonbingen/Minecraft-BossTools-Addon/tree/1.18.2/src/generated/resources/assets/beyond_earth_giselle_addon/lang
2. if you has translation json file, click 'add file' and 'upload files'
3. Else if you don't have, click 'add file' and 'create new file'
3.1. Enter file name as 'zh_cn.json' and write translation

**Comment by Mai-xiyu** [comment]
Okay, I'll do that, but the damn power system is out



---Original---
From: ***@***.***&gt;
Date: Wed, Oct 12, 2022 12:06 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [gisellevonbingen/Minecraft-BossTools-Addon] Add the translationfile zh_cn.json (PR #102)




 
Could you try again as follow below steps?
  
go to https://github.com/gisellevonbingen/Minecraft-BossTools-Addon/tree/1.18.2/src/generated/resources/assets/beyond_earth_giselle_addon/lang
 
if you has translation json file, click 'add file', and 'upload files'
 
Else if don't have, click 'add file' and 'create new file'
 3.1. Enter file name as 'zh_cn.json' and write translation

**Comment by Mai-xiyu** [comment]
I have submitted, please take a look at zh_cn.json

**Comment by gisellevonbingen** [comment]
Ok, almost complete
But file you submitted what is included in other branch
Could you create  a new pull request instead of this?

https://github.com/gisellevonbingen/Minecraft-BossTools-Addon/pulls
Click 'New pull request' in above url,
Follow bellow steps

image
image

**Comment by Mai-xiyu** [comment]
tomorrow&nbsp;



---Original---
From: ***@***.***&gt;
Date: Wed, Oct 12, 2022 20:32 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [gisellevonbingen/Minecraft-BossTools-Addon] Add the translationfile zh_cn.json (PR #102)




 
Ok, almost complete
 But file you submitted what is included in other branch
 Could you create  a new pull request instead of this?
 
https://github.com/gisellevonbingen/Minecraft-BossTools-Addon/pulls
 Click 'New pull request' in above url,
 Follow bellow steps

**Comment by gisellevonbingen** [comment]
Replace to #103

**Comment by Mai-xiyu** [comment]
You can merge zh_cn to 1.18.1




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gisellevonbingen/Minecraft-BossTools-Addon"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月13日(星期四) 中午11:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [gisellevonbingen/Minecraft-BossTools-Addon] Add the translation file zh_cn.json (PR #102)





 
Replace to #103

**Comment by gisellevonbingen** [comment]
Do you play in 1.18.1?

**Comment by Mai-xiyu** [comment]
yes
&nbsp;


哈
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月13日(星期四) 中午1:39
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [gisellevonbingen/Minecraft-BossTools-Addon] Add the translation file zh_cn.json (PR #102)





 
Do you play in 1.18.1?

**Comment by gisellevonbingen** [comment]
OK, i will merge it soon

**Comment by gisellevonbingen** [comment]
Then, can you create zh_cn.json file with some change translation?
Some features are different between 1.18.1 and 1.18.2.

1.18.1 version's lang file can found here.
https://github.com/gisellevonbingen/Minecraft-BossTools-Addon/tree/1.18.1/src/generated/resources/assets/beyond_earth_giselle_addon/lang

If you commit changes.
Plz create new pull request via same steps.
But select 1.18.1 instead of 1.18.2

**Comment by Mai-xiyu** [comment]
ok
&nbsp;


哈
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月13日(星期四) 下午2:01
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [gisellevonbingen/Minecraft-BossTools-Addon] Add the translation file zh_cn.json (PR #102)





 
然后，是否可以创建带有zh_cn.json文件并进行一些更改转换？
 1.18.1 和 1.18.2 之间的某些功能不同。
 
1.18.1 版本的 lang 文件可以在这里找到。
 https://github.com/gisellevonbingen/Minecraft-BossTools-Addon/tree/1.18.1/src/generated/resources/assets/beyond_earth_giselle_addon/lang
 
如果提交更改。
请通过相同的步骤创建新的拉取请求。
但选择 1.18.1 而不是 1.18.2
 
—
 直接回复此电子邮件、在 GitHub 上查看或取消订阅。
您收到此消息是因为您创作了该线程。Message ID: ***@***.***&gt;

**Comment by Mai-xiyu** [comment]
Maybe you don't know one thing, I created it with the en_us.lang of 1.18.1 zh_cn so it also fits 1.18.1 and 1.18.2




哈
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gisellevonbingen/Minecraft-BossTools-Addon"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月13日(星期四) 下午2:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [gisellevonbingen/Minecraft-BossTools-Addon] Add the translation file zh_cn.json (PR #102)





 
Then, can you create zh_cn.json file with some change translation?
 Some features are different between 1.18.1 and 1.18.2.
 
1.18.1 version's lang file can found here.
 https://github.com/gisellevonbingen/Minecraft-BossTools-Addon/tree/1.18.1/src/generated/resources/assets/beyond_earth_giselle_addon/lang
 
If you commit changes.
 Plz create new pull request via same steps.
 But select 1.18.1 instead of 1.18.2

**Comment by gisellevonbingen** [comment]
Enchantment's description text is changed in 1.18.2
Even if can use it 1.18.1 too?

**Comment by Mai-xiyu** [comment]
Yes
&nbsp;


哈
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月13日(星期四) 下午2:08
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [gisellevonbingen/Minecraft-BossTools-Addon] Add the translation file zh_cn.json (PR #102)






附魔的描述文字在1.18.2改了 就算1.18.1也能用？ — 直接回复此电子邮件，在 GitHub 上查看它，或取消订阅您收到此邮件是因为您创作了该主题。消息编号： <gisellevonbingen/Minecraft-BossTools-Addon/pull/102/c1277075914
@

github与&gt;
.
.

**Comment by gisellevonbingen** [comment]
genius.

**Comment by Mai-xiyu** [comment]
Do I still need to pull a request?




哈
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gisellevonbingen/Minecraft-BossTools-Addon"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月13日(星期四) 下午2:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [gisellevonbingen/Minecraft-BossTools-Addon] Add the translation file zh_cn.json (PR #102)





 
Enchantment's description text is changed in 1.18.2
 Even if can use it 1.18.1 too?

**Comment by gisellevonbingen** [comment]
No need.
I will comment when new version released in 1.18.1

**Comment by Mai-xiyu** [comment]
ok&nbsp;
&nbsp;


哈
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月13日(星期四) 下午2:11
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [gisellevonbingen/Minecraft-BossTools-Addon] Add the translation file zh_cn.json (PR #102)






没必要。我会在 1.18.1 发布新版本时发表评论 — 直接回复此电子邮件，在 GitHub 上查看或取消订阅您收到此邮件是因为您撰写了该主题。消息编号： <gisellevonbingen/Minecraft-BossTools-Addon/pull/102/c1277078426
@

github与&gt;
.
.

**Comment by Mai-xiyu** [comment]
Can you bring down the mod's adaptive game version to 1.16.4? Or recreate the 1.16.4 mod?I want players on NetEase Minecraft to play this mod




哈
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gisellevonbingen/Minecraft-BossTools-Addon"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月13日(星期四) 下午2:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [gisellevonbingen/Minecraft-BossTools-Addon] Add the translation file zh_cn.json (PR #102)





 
No need.
 I will comment when new version released in 1.18.1

**Comment by gisellevonbingen** [comment]
Is impossible 1.16.5?
1.16.4 was expired from forge

**Comment by Mai-xiyu** [comment]
NetEase Minecraft 1.16 series only has 1.16.4, and the 1.18 series has only 1.18.1
&nbsp;


哈
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月13日(星期四) 下午2:24
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [gisellevonbingen/Minecraft-BossTools-Addon] Add the translation file zh_cn.json (PR #102)





 
Is impossible 1.16.5?
 1.16.4 was expired from forge

**Comment by gisellevonbingen** [comment]
So sad,
Can you test 1.16.5 file with minecraft 1.16.4?
Perhaps it can not occur error.

**Comment by Mai-xiyu** [comment]
ok
&nbsp;


哈
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月13日(星期四) 下午2:28
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [gisellevonbingen/Minecraft-BossTools-Addon] Add the translation file zh_cn.json (PR #102)






太伤心了，你能用 minecraft 1.16.4 测试 1.16.5 文件吗？也许它不能发生错误。 — 直接回复此电子邮件，在 GitHub 上查看它，或取消订阅您收到此邮件是因为您创作了该主题。消息编号： <gisellevonbingen/Minecraft-BossTools-Addon/pull/102/c1277093608
@
github与&gt;


.
.

**Comment by gisellevonbingen** [comment]
1.18.1 will be released soon at https://www.curseforge.com/minecraft/mc-mods/space-bosstools-giselle-addon/files/4027388
now under review

**Comment by gisellevonbingen** [comment]
> NetEase Minecraft 1.16 series only has 1.16.4, and the 1.18 series has only 1.18.1 &nbsp; 哈 ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2022年10月13日(星期四) 下午2:24 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [gisellevonbingen/Minecraft-BossTools-Addon] Add the translation file zh_cn.json (PR #102) Is impossible 1.16.5? 1.16.4 was expired from forge — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

I realized just right now,
Space-BossTools is not support 1.16.4.
So sorry late reply.

**Comment by Mai-xiyu** [comment]
I'm finishing the 1.16.5 zh_cn tonight with tomorrow's pull request

**Pull request closed without merging**
